version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-apache-directory-index/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-bitbucket-pr/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-git/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-github-release/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-k8s/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-keyval/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-maven/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-mock/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-oss-github-pr/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-pool/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-registry-image/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-registry-tag/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-rss/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-s3/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-semver/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-slack-alert/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-sonarqube/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-terraform/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-time/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/concourse-ts-resource-tracker/
    schedule:
      interval: daily
