ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG concourse-ts-cli
ARG concourse-ts
ARG concourse-ts-recipe-auto-pipeline
ARG concourse-ts-recipe-oci-build
ARG concourse-ts-recipe-npm-dependencies
ARG typescript

RUN yarn global add \
  --non-interactive \
  --production=false \
  --network-concurrency=5 \
  @decentm/concourse-ts-cli@${concourse-ts-cli} \
  @decentm/concourse-ts@${concourse-ts} \
  @decentm/concourse-ts-recipe-auto-pipeline@${concourse-ts-recipe-auto-pipeline} \
  @decentm/concourse-ts-recipe-oci-build@${concourse-ts-recipe-oci-build} \
  @decentm/concourse-ts-recipe-npm-dependencies@${concourse-ts-recipe-npm-dependencies} \
  typescript@${TYPESCRIPT_VERSION}

ENV NODE_PATH="${NODE_PATH}:/usr/local/share/.config/yarn/global/node_modules"

CMD ["concourse-ts"]
