ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG concourse_ts_cli
ARG concourse_ts
ARG concourse_ts_recipe_auto_pipeline
ARG concourse_ts_recipe_oci_build
ARG concourse_ts_recipe_npm_dependencies
ARG typescript

RUN yarn global add \
  --non-interactive \
  --production=false \
  --network-concurrency=5 \
  @decentm/concourse-ts-cli@${concourse_ts_cli} \
  @decentm/concourse-ts@${concourse_ts} \
  @decentm/concourse-ts-recipe-auto-pipeline@${concourse_ts_recipe_auto_pipeline} \
  @decentm/concourse-ts-recipe-oci-build@${concourse_ts_recipe_oci_build} \
  @decentm/concourse-ts-recipe-npm-dependencies@${concourse_ts_recipe_npm_dependencies} \
  typescript@${typescript}

ENV NODE_PATH="${NODE_PATH}:/usr/local/share/.config/yarn/global/node_modules"

CMD ["concourse-ts"]
