jobs:
  - name: myjob
    plan:
      - attempts: 3
        timeout: 6h
        get: test
        trigger: true
        version: latest
      - attempts: 3
        timeout: 6h
        try:
          attempts: 3
          timeout: 6h
          task: testtask
          config:
            platform: linux
            run:
              path: echo
              args:
                - '[concourse-ts] "run" not implemented, skipping...'
              dir: .
            inputs:
              - name: testi
                optional: false
                path: ./asd
          privileged: false
    build_log_retention:
      builds: 10
      minimum_succeeded_builds: 7
    disable_manual_trigger: false
    interruptible: true
    max_in_flight: 3
    public: false
    serial: false
resource_types:
  - name: test
    type: registry-image
    check_every: 1m
    privileged: false
    unique_version_history: false
resources:
  - name: test
    type: test
    check_every: 1m
    public: false
