export const DOCKER_MAX_CONCURRENT_DOWNLOADS_PUBLIC = 3
export const DOCKER_MAX_CONCURRENT_UPLOADS_PUBLIC = 3

export const DOCKER_MAX_CONCURRENT_DOWNLOADS_PRIVATE = 10
export const DOCKER_MAX_CONCURRENT_UPLOADS_PRIVATE = 10
