tasks:
  build:
    command: pkgroll
    args:
      - --clean-dist
      - --sourcemap
    options:
      cache: true
    outputs:
      - dist

  lint:
    command: eslint
    args:
      - '.'
    options:
      cache: true

  test:
    command: c8
    args:
      - --100
      - --reporter=lcov
      - --reporter=text
      - ava
    options:
      cache: true
