name: npm-publish

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lock-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependencies
        run: |
          set -exu
          yarn --frozen-lockfile --non-interactive

      - name: Build
        run: |
          set -exu
          yarn build
          tar -czf build.tar.gz dist/

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Publish to NPM
        if: steps.check.outputs.changed == 'true'
        run: |
          set -exu
          yarn publish build.tar.gz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
