name: npm-publish

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lock-

      - name: Dependencies
        run: |
          set -exu
          yarn --frozen-lockfile --non-interactive

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release

      - name: Setup Node
        uses: actions/setup-node@v3
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM
        if: steps.release.outputs.released == 'true'
        run: |
          set -exu
          yarn publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
