name: npm-publish

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  affected:
    name: Determine affected packages
    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}

    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}

    steps:
      - name: Calculate Affected Projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'test,build'
          maxDistribution: 1

  publish:
    name: Publish ${{ matrix.target }}

    needs:
      - affected

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.affected.outputs.matrix) }}

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lock-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Dependencies
        run: |
          set -exu
          yarn --frozen-lockfile --non-interactive

      - run: yarn nx workspace-lint
      - run: yarn nx format:check

      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      - run: yarn nx affected --target=build --parallel=3
