name: npm-publish

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    name: Publish packages

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lock-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Dependencies
        run: |
          set -exu
          yarn --frozen-lockfile --non-interactive

      - run: yarn nx workspace-lint

      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      - run: yarn nx affected --target=build --parallel=3

      # Publish new versions of affected packages
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -exu

          for d in dist/packages/* ; do
            cd "$d"
            yarn publish . --access public
            cd -
          done
