name: wiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            lock-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          yarn --frozen-lockfile --non-interactive

      - name: Generate docs
        run: |
          set -exu
          yarn docs

      - name: Upload Documentation to Wiki
        uses: cmbrose/github-docs-to-wiki@v0.20
        with:
          githubToken: ${{ secrets.WIKI_PAT }}
          rootDocsFolder: docs
          convertRootReadmeToHomePage: true
          useHeaderForWikiName: true
